
#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx

  - name: name of truth, what truth
    debug: var=ansible_os_family

  - block: #Debian block install nginx and starting service

      - name: installing nginx
        ansible.builtin.package:
          name: nginx
          state: latest

      - name: create ssl directory
        ansible.builtin.file:
          path: /etc/nginx/ssl
          state: directory
          mode: '0755'

      - name: jinja template nginx.conf.j2
        ansible.builtin.template:
          src: nginx.conf.j2
          dest: /etc/nginx/nginx.conf
          mode: '0655'
        notify: Перезапустим nginx

      - name: Убедимся, что nginx запущен
        ansible.builtin.service:
          name: nginx
          state: started
          enabled: true
