#SPDX-License-Identifier: MIT-0
---
# tasks file for certs
    - name: Создание директории для сертификатов
        file:
          path: "{{ cert_path }}"
          state: directory
          owner: root
          group: root
          mode: '0755'

    - name: Сгенерировать приватный ключ
      community.crypto.openssl_privatekey:
        path: "{{ key_file }}"
        size: 2048
        type: RSA

    - name: Сгенерировать самоподписанный сертификат
      community.crypto.openssl_certificate:
        path: "{{ crt_file }}"
        privatekey_path: "{{ key_file }}"
        provider: selfsigned
        common_name: "{{ domain_name }}"
        days: "{{ days_valid }}"
